# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b810722d1a42ba760c06dfe34a75cbc0508918d67b8168899bff3e698c43f6fe34b4bd034a60620385c713aff9a2e0f9d204229d751c2ba15da4afb7377e4f1

test:
  secret_key_base: 748db73ad42d6f64522d899dc5fee81ad547c080a3e4292a97b2f29ddc16cf6ede86ce6200c49dc0c251928b7211f85d7e861e56eb70ac483dc0dd2d5be6548e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
